aibot:
  hardware_interface:
     loop_hz: 10 # hz
     joints:
      - arm_base_rot_link_joint
      - arm_first_link_joint
      - arm_second_link_joint
      - arm_third_link_joint
      - arm_fourth_link_joint
      - arm_second_motor_link_joint
      - arm_second_connector_link_joint
  controller:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100
    arm_controller:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - arm_base_rot_link_joint
        - arm_first_link_joint
        - arm_second_link_joint
        - arm_third_link_joint
        - arm_fourth_link_joint
        - arm_second_motor_link_joint
        - arm_second_connector_link_joint
